PyData Markdown file
PyconUK/2017.pyconuk.org pull request #26
Opened 2017-07-17 18:16 UTC by timvg80

Here is a draft of the markdown file containing the relevant information for the PyData track

2017-07-18 21:39 UTC, alexwlchan approved these changes
Two very minor things, but otherwise LGTM.

Thanks @timvg80!

2017-07-18 21:39 UTC, alexwlchan commented on pages/pydata.md
> +The time allocated for each talk is 30 minutes. If you are happy to receive any questions from the audience (this is not compulsory), then please allow time for these.
I could have sworn it was 25 minutes, but I could be wrong. I need to double check.

2017-07-18 21:39 UTC, alexwlchan commented on pages/pydata.md
> +If anyone would like to see examples of the sorts of talks that have been presented at PyData conferences in UK the in the past, these can be seen on the [PyData YouTube channel](https://www.youtube.
nit: full stop?

2017-07-19 14:46 UTC, inglesp requested changes
Hi @timvg80, thanks for this.

I've made some suggested changes inline.

A couple of minor things: please can you always refer to the conference as "PyCon UK" to distinguish us from other PyCons; and can you decide on whether it's "data science" or "data-science"?

2017-07-19 14:46 UTC, inglesp commented on pages/pydata.md
> +The time allocated for each talk is 30 minutes. If you are happy to receive any questions from the audience (this is not compulsory), then please allow time for these.
Yes: we've decided that talks are 25 minutes long.  Sorry for not telling you @timvg80.  We should add this to the  main CFP page too.

2017-07-19 14:46 UTC, inglesp commented on pages/pydata.md
> +## What we are looking for
It's not clear that this section is about the CFP.  You could add a line to the paragraph above saying something like: "We will be hosting a number of talks and workshops about data science at the the conference, and we are looking for members of the PyData community to submit proposals to the [conference CFP](https://hq.pyconuk.org/cfp/proposals/new/)."

2017-07-19 14:46 UTC, inglesp commented on pages/pydata.md
> +This track is mainly focussed on looking for speakers who wish to share their experiences of using Python in data-science. Examples such as:
This feels a bit wordy -- could you change the opening to "We are looking for speakers..."?

2017-07-22 14:35 UTC, timvg80 commented
Hi Alex and Peter. I have made some changes now, and have pushed them to my master branch.

2017-07-22 14:46 UTC, alexwlchan requested changes
Thanks, looks pretty good! A few more minor things.

2017-07-22 14:46 UTC, alexwlchan commented on pages/pydata.md
> +This year, for the first time, the teams at PyConUK and [PyData London](http://london.pydata.org/) are joining forces to deliver a data science focussed track at the conference. We will be hosting a
nit: the conference name is “PyCon UK”, not “PyConUK”

(@inglesp: I’m sure we used to have CI checks for this?)

2017-07-22 14:46 UTC, alexwlchan commented on pages/pydata.md
> +Both PyConUK and PyData are thriving communities that want to help people to learn and develop their tech skills. We welcome talks from all backgrounds and all abilities, across both academia and ind
Up to you, but I wonder if it might be nice to have a link to http://2017.pyconuk.org/diversity-accessibility-inclusion/ in this paragraph?

2017-07-22 14:52 UTC, timvg80 commented on pages/pydata.md
> +This year, for the first time, the teams at PyConUK and [PyData London](http://london.pydata.org/) are joining forces to deliver a data science focussed track at the conference. We will be hosting a
Hi Alex... of course! I've fixed and pushed those changes now.

2017-07-22 14:56 UTC, alexwlchan approved these changes
Okay, I don’t think I have any other comments. Anything else from you, @inglesp?

2017-07-22 20:29 UTC, inglesp approved these changes

2017-07-22 20:29 UTC, merged

2017-07-23 11:23 UTC, timvg80 commented
Hi both,

Thanks for letting me know. I've just had a look now, and it looks great! I
have let the PyData team know in London as well. Just one thing... I
noticed that I had made an error in some word ordering in one of the
sections, so I have just corrected that and made another pull request.
Sorry for that.

Tim

On 22 July 2017 at 21:29, Peter Inglesby <notifications@github.com> wrote:

> Merged #26 <https://github.com/PyconUK/2017.pyconuk.org/pull/26>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/PyconUK/2017.pyconuk.org/pull/26#event-1174990676>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGwVVLu0T7C9bN6TC9snwxwPm6awBLo8ks5sQlu2gaJpZM4OaV9t>
> .
>