Update Education track page
PyconUK/2017.pyconuk.org pull request #35
Opened 2017-08-04 14:26 UTC by bennuttall

I've added some information and @MissPhilbin and @ntoll have contributed

2017-08-04 15:11 UTC, alexwlchan requested changes

2017-08-04 15:11 UTC, alexwlchan commented on pages/education.md
> +their digital making and computing journey. It's a two-day CPD event held at
minor: I had to google “CPD event” to know what the acronym stands for, but I’m guessing you expect teachers to understand this?

2017-08-04 15:11 UTC, alexwlchan commented on pages/education.md
> +**[Code Club](https://www.codeclub.org.uk/)**: the ever popular PyConUK Code
“PyConUK” needs a space, which is what’s breaking the build

2017-08-04 15:11 UTC, alexwlchan commented on pages/education.md
> +PyConUK ticket unless you are also planning to attend on Saturday.
ditto above

2017-08-04 16:26 UTC, bennuttall commented on pages/education.md
> +their digital making and computing journey. It's a two-day CPD event held at
Oh I thought @ntoll had changed this but I guess he just commented. @MissPhilbin - it's your call.

2017-08-04 17:19 UTC, alexwlchan approved these changes
Okay, I’m happy to merge this as-is. Shout if you want to change CPD, and if not I’ll merge it when I get home.

2017-08-04 21:13 UTC, merged

2017-08-07 10:39 UTC, bennuttall commented
Thanks! :+1: