Add information about hotels in Cardiff
PyconUK/2017.pyconuk.org pull request #48
Opened 2017-08-19 10:44 UTC by alexwlchan

Most of the text is copied wholesale from the PyCon UK 2016 site, with just the information about which hotels are offering us special rates being rearranged slightly.

2017-08-19 10:49 UTC, alexwlchan commented
Okay, so this is breaking because http-crawler doesn’t know about mailto: links. Guess it’s time for me to finally fix that…

Related: https://github.com/inglesp/http-crawler/issues/6

2017-08-19 10:49 UTC, alexwlchan commented
While I prepare a patch for that, can I get another pair of eyes on the content please?

2017-08-20 15:07 UTC, inglesp requested changes

2017-08-20 15:07 UTC, inglesp commented on pages/accommodation.md
> +as you can**.
There's only one hotel in this list!

2017-08-20 15:07 UTC, inglesp commented on pages/accommodation.md
> +double or twin room.
Do we know what the negotiated rates are?

2017-08-20 15:07 UTC, inglesp commented on pages/accommodation.md
> +Please use the code *trip1* when booking (phone or email).
Presumably this line is a hangover from last year.

2017-08-20 15:07 UTC, inglesp commented on pages/accommodation.md
> +#### Travelodge Hotels
Should these, and the Premier Inn, be listed under "Other Hotels"?

2017-08-21 07:30 UTC, alexwlchan commented on pages/accommodation.md
> +double or twin room.
I don’t, no.

2017-08-21 07:30 UTC, alexwlchan commented on pages/accommodation.md
> +as you can**.
Oops. Plurals are hard.

2017-08-21 07:31 UTC, alexwlchan commented on pages/accommodation.md
> +Please use the code *trip1* when booking (phone or email).
Mmmm. I stayed there last year, and this was a generic voucher (although it is a hangover from last year). I’ll remove it for now.

2017-08-21 07:31 UTC, alexwlchan commented on pages/accommodation.md
> +#### Travelodge Hotels
Yep, think that’s a holdover from last year.

2017-08-21 15:30 UTC, alexwlchan commented
@inglesp I’ve addressed your comments and rebased against current master; anything else?

2017-08-23 21:27 UTC, merged

2017-08-24 08:59 UTC, ntoll commented
Please see #52 WRT information missing from this PR.